import { PecsCardType } from './types';
// src/constants.ts

// Mapeamento limpo para títulos do sistema
export const CATEGORY_NAMES: Record<string, string> = {
  home: 'Início',
  sobre: 'Sobre Mim',
  familia: 'Família',
  comer: 'Quero Comer',
  brincar: 'Quero Brincar',
  sentimentos: 'Sentimentos',
  higiene: 'Higiene',
};

// Seus mais de 400 cards originais continuam aqui como a base padrão do sistema
export const INITIAL_CARDS: PecsCardType[] = [
  {
    id: 'sobre-mim',
    label: 'sobre mim',
    icon: 'user',
    type: 'category',
    target: 'sobre',
    bgColor: 'bg-indigo-50',
    borderColor: 'border-indigo-200',
    color: 'text-indigo-600',
  },
  {
    id: 'familia-cat',
    label: 'família',
    icon: 'users',
    type: 'category',
    target: 'familia',
    bgColor: 'bg-emerald-50',
    borderColor: 'border-emerald-200',
    color: 'text-emerald-600',
  },
  {
    id: 'comer-cat',
    label: 'comer',
    icon: 'utensils',
    type: 'category',
    target: 'comer',
    bgColor: 'bg-amber-50',
    borderColor: 'border-amber-200',
    color: 'text-amber-600',
  },
  {
    id: 'brincar-cat',
    label: 'brincar',
    icon: 'gamepad',
    type: 'category',
    target: 'brincar',
    bgColor: 'bg-sky-50',
    borderColor: 'border-sky-200',
    color: 'text-sky-600',
  },
  {
    id: 'ir-cat',
    label: 'ir',
    icon: 'footprints',
    type: 'category',
    target: 'ir',
    bgColor: 'bg-purple-50',
    borderColor: 'border-purple-200',
    color: 'text-purple-600',
  },
  {
    id: 'querer-cat',
    label: 'querer',
    icon: 'hand',
    type: 'category',
    target: 'querer',
    bgColor: 'bg-blue-50',
    borderColor: 'border-blue-200',
    color: 'text-blue-600',
  },
  {
    id: 'sentimentos-cat',
    label: 'sentimentos',
    icon: 'smile',
    type: 'category',
    target: 'sentimentos',
    bgColor: 'bg-rose-50',
    borderColor: 'border-rose-200',
    color: 'text-rose-600',
  },
  {
    id: 'ajuda',
    label: 'ajuda',
    icon: 'helpCircle',
    type: 'item',
    bgColor: 'bg-amber-100',
    borderColor: 'border-amber-300',
    color: 'text-amber-700',
  },
  {
    id: 'sim',
    label: 'sim',
    icon: 'checkCircle',
    type: 'item',
    bgColor: 'bg-green-100',
    borderColor: 'border-green-300',
    color: 'text-green-700',
  },
  {
    id: 'nao',
    label: 'não',
    icon: 'xCircle',
    type: 'item',
    bgColor: 'bg-red-100',
    borderColor: 'border-red-300',
    color: 'text-red-700',
  },
  {
    id: 'eu',
    label: 'eu',
    icon: 'smile',
    type: 'item',
    bgColor: 'bg-cyan-50',
    borderColor: 'border-cyan-200',
    color: 'text-cyan-700',
  },
  {
    id: 'voce',
    label: 'você',
    icon: 'search',
    type: 'item',
    bgColor: 'bg-slate-50',
    borderColor: 'border-slate-200',
    color: 'text-slate-700',
  },

  // --- SOBRE MIM ---
  {
    id: 'meu-nome',
    label: 'meu nome é',
    icon: 'contact',
    type: 'item',
    target: 'sobre',
    bgColor: 'bg-white',
    borderColor: 'border-indigo-100',
    color: 'text-indigo-600',
  },
  {
    id: 'eu-sou',
    label: 'eu sou',
    icon: 'userCheck',
    type: 'item',
    target: 'sobre',
    bgColor: 'bg-white',
    borderColor: 'border-indigo-100',
    color: 'text-indigo-600',
  },
  {
    id: 'moro-em',
    label: 'moro em',
    icon: 'homeIcon',
    type: 'item',
    target: 'sobre',
    bgColor: 'bg-white',
    borderColor: 'border-indigo-100',
    color: 'text-indigo-600',
  },
  {
    id: 'minha-idade',
    label: 'minha idade',
    icon: 'cake',
    type: 'item',
    target: 'sobre',
    bgColor: 'bg-white',
    borderColor: 'border-indigo-100',
    color: 'text-indigo-600',
  },
  {
    id: 'telefone',
    label: 'telefone',
    icon: 'phone',
    type: 'item',
    target: 'sobre',
    bgColor: 'bg-white',
    borderColor: 'border-indigo-100',
    color: 'text-indigo-600',
  },

  // --- FAMÍLIA ---
  {
    id: 'papai',
    label: 'papai',
    icon: 'user',
    type: 'item',
    target: 'familia',
    bgColor: 'bg-white',
    borderColor: 'border-emerald-100',
    color: 'text-emerald-600',
  },
  {
    id: 'mamae',
    label: 'mamãe',
    icon: 'user',
    type: 'item',
    target: 'familia',
    bgColor: 'bg-white',
    borderColor: 'border-emerald-100',
    color: 'text-pink-500',
  },
  {
    id: 'vovo-m',
    label: 'vovô',
    icon: 'userCheck',
    type: 'item',
    target: 'familia',
    bgColor: 'bg-white',
    borderColor: 'border-emerald-100',
    color: 'text-emerald-700',
  },
  {
    id: 'vovo-f',
    label: 'vovó',
    icon: 'userCheck',
    type: 'item',
    target: 'familia',
    bgColor: 'bg-white',
    borderColor: 'border-emerald-100',
    color: 'text-pink-600',
  },
  {
    id: 'irmao',
    label: 'irmão',
    icon: 'baby',
    type: 'item',
    target: 'familia',
    bgColor: 'bg-white',
    borderColor: 'border-emerald-100',
    color: 'text-sky-500',
  },
  {
    id: 'irma',
    label: 'irmã',
    icon: 'baby',
    type: 'item',
    target: 'familia',
    bgColor: 'bg-white',
    borderColor: 'border-emerald-100',
    color: 'text-rose-400',
  },

  // --- COMER ---
  {
    id: 'maca',
    label: 'maçã',
    icon: 'apple',
    type: 'item',
    target: 'comer',
    bgColor: 'bg-white',
    borderColor: 'border-amber-100',
    color: 'text-red-500',
  },
  {
    id: 'cookie',
    label: 'biscoito',
    icon: 'cookie',
    type: 'item',
    target: 'comer',
    bgColor: 'bg-white',
    borderColor: 'border-amber-100',
    color: 'text-amber-700',
  },
  {
    id: 'pizza',
    label: 'pizza',
    icon: 'pizza',
    type: 'item',
    target: 'comer',
    bgColor: 'bg-white',
    borderColor: 'border-amber-100',
    color: 'text-amber-500',
  },
  {
    id: 'leite',
    label: 'leite',
    icon: 'glassWater',
    type: 'item',
    target: 'comer',
    bgColor: 'bg-white',
    borderColor: 'border-amber-100',
    color: 'text-sky-400',
  },
  {
    id: 'suco',
    label: 'suco',
    icon: 'cupSoda',
    type: 'item',
    target: 'comer',
    bgColor: 'bg-white',
    borderColor: 'border-amber-100',
    color: 'text-orange-500',
  },
  {
    id: 'agua',
    label: 'água',
    icon: 'droplet',
    type: 'item',
    target: 'comer',
    bgColor: 'bg-white',
    borderColor: 'border-amber-100',
    color: 'text-blue-500',
  },

  // --- SENTIMENTOS ---
  {
    id: 'feliz',
    label: 'feliz',
    icon: 'smile',
    type: 'item',
    target: 'sentimentos',
    bgColor: 'bg-white',
    borderColor: 'border-rose-100',
    color: 'text-yellow-500',
  },
  {
    id: 'triste',
    label: 'triste',
    icon: 'frown',
    type: 'item',
    target: 'sentimentos',
    bgColor: 'bg-white',
    borderColor: 'border-rose-100',
    color: 'text-blue-400',
  },
  {
    id: 'bravo',
    label: 'bravo',
    icon: 'angry',
    type: 'item',
    target: 'sentimentos',
    bgColor: 'bg-white',
    borderColor: 'border-rose-100',
    color: 'text-red-600',
  },
  {
    id: 'cansado',
    label: 'cansado',
    icon: 'moon',
    type: 'item',
    target: 'sentimentos',
    bgColor: 'bg-white',
    borderColor: 'border-rose-100',
    color: 'text-purple-500',
  },
  {
    id: 'assustado',
    label: 'assustado',
    icon: 'ghost',
    type: 'item',
    target: 'sentimentos',
    bgColor: 'bg-white',
    borderColor: 'border-rose-100',
    color: 'text-violet-500',
  },

  // --- BRINCAR ---
  {
    id: 'bola',
    label: 'bola',
    icon: 'flower', // fallback clean circular or similar
    type: 'item',
    target: 'brincar',
    bgColor: 'bg-white',
    borderColor: 'border-sky-100',
    color: 'text-sky-600',
  },
  {
    id: 'boneca',
    label: 'boneca',
    icon: 'baby',
    type: 'item',
    target: 'brincar',
    bgColor: 'bg-white',
    borderColor: 'border-sky-100',
    color: 'text-pink-400',
  },
  {
    id: 'carrinho',
    label: 'carrinho',
    icon: 'car',
    type: 'item',
    target: 'brincar',
    bgColor: 'bg-white',
    borderColor: 'border-sky-100',
    color: 'text-emerald-500',
  },
  {
    id: 'blocos',
    label: 'blocos',
    icon: 'layoutGrid',
    type: 'item',
    target: 'brincar',
    bgColor: 'bg-white',
    borderColor: 'border-sky-100',
    color: 'text-amber-500',
  },
  {
    id: 'puzle',
    label: 'quebra-cabeça',
    icon: 'puzzle',
    type: 'item',
    target: 'brincar',
    bgColor: 'bg-white',
    borderColor: 'border-sky-100',
    color: 'text-indigo-500',
  },

  // --- IR ---
  {
    id: 'escola',
    label: 'escola',
    icon: 'school',
    type: 'item',
    target: 'ir',
    bgColor: 'bg-white',
    borderColor: 'border-purple-100',
    color: 'text-indigo-600',
  },
  {
    id: 'parque',
    label: 'parque',
    icon: 'trees',
    type: 'item',
    target: 'ir',
    bgColor: 'bg-white',
    borderColor: 'border-purple-100',
    color: 'text-emerald-600',
  },
  {
    id: 'casa',
    label: 'casa',
    icon: 'homeIcon',
    type: 'item',
    target: 'ir',
    bgColor: 'bg-white',
    borderColor: 'border-purple-100',
    color: 'text-blue-500',
  },
  {
    id: 'banheiro',
    label: 'banheiro',
    icon: 'bath',
    type: 'item',
    target: 'ir',
    bgColor: 'bg-white',
    borderColor: 'border-purple-100',
    color: 'text-cyan-500',
  },
  {
    id: 'medico',
    label: 'médico',
    icon: 'stethoscope',
    type: 'item',
    target: 'ir',
    bgColor: 'bg-white',
    borderColor: 'border-purple-100',
    color: 'text-rose-500',
  },

  // --- QUERER ---
  {
    id: 'querer-eu',
    label: 'eu quero',
    icon: 'hand',
    type: 'item',
    target: 'querer',
    bgColor: 'bg-white',
    borderColor: 'border-blue-100',
    color: 'text-blue-600',
  },
  {
    id: 'me-da',
    label: 'me dá',
    icon: 'hand',
    type: 'item',
    target: 'querer',
    bgColor: 'bg-white',
    borderColor: 'border-blue-100',
    color: 'text-indigo-600',
  },
  {
    id: 'por-favor',
    label: 'por favor',
    icon: 'heart',
    type: 'item',
    target: 'querer',
    bgColor: 'bg-white',
    borderColor: 'border-blue-100',
    color: 'text-red-500',
  },
  {
    id: 'terminar',
    label: 'terminar',
    icon: 'checkSquare',
    type: 'item',
    target: 'querer',
    bgColor: 'bg-white',
    borderColor: 'border-blue-100',
    color: 'text-emerald-500',
  },
];